# Generated by Django 3.0.3 on 2020-03-06 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
